Add wiki page for Horizons tool
OpenSpace/openspace.github.io pull request #22
Opened 2022-06-01 14:56 UTC by Roxeena

2022-06-21 12:00 UTC, WeirdRubberDuck commented on docs/builders/ephemeris/horizons-gui.md
> +Since version 0.18.0 of OpenSpace there is a new feature that allows our users to access Horizons data directly via OpenSpace with no need to go to the [Horizons website](https://ssd.jpl.nasa.gov/hor
"...directly via OpenSpace with no need to go to the [Horizons website]" -> "directly via OpenSpace, without needing to go to the [Horizons website]"

2022-06-21 12:42 UTC, WeirdRubberDuck requested changes

2022-06-21 12:42 UTC, WeirdRubberDuck commented on docs/builders/ephemeris/horizons-gui.md
> +Since version 0.18.0 of OpenSpace there is a new feature that allows our users to access Horizons data directly via OpenSpace with no need to go to the [Horizons website](https://ssd.jpl.nasa.gov/hor
"...directly via OpenSpace with no need to go to the [Horizons website]" -> "directly via OpenSpace, without needing to go to the [Horizons website]"

2022-06-21 12:42 UTC, WeirdRubberDuck commented on docs/builders/ephemeris/horizons-gui.md
> +In the new window there is a few places where you can input specifications for what Horizons data you want to access. Once you have put in the input you can press the *Save* button at the bottom of t
"Once you have put in the input you can press the *Save* button at the bottom of the window" -> "Once you have entered all information you can press the *Save* button at the bottom of the window"

2022-06-21 12:42 UTC, WeirdRubberDuck commented on docs/builders/ephemeris/horizons-gui.md
> +In the new window there is a few places where you can input specifications for what Horizons data you want to access. Once you have put in the input you can press the *Save* button at the bottom of t
```
This process is very similar to how you would do it on the Horizons web page that you can read more about [here](horizons-web).
```
->
```
This process is very similar to how you would do it on the Horizons web page. Read more about that [here](horizons-web).
```

(obs, switched commenting style from here on)

2022-06-21 12:42 UTC, WeirdRubberDuck commented on docs/builders/ephemeris/horizons-gui.md
> +Here you specify where on your computer you want the data to be stored once it has been downloaded. You can click the *Browse* button to browse with the file explorer to specify where the data should
The first bit here seems a bit wordy to me. Maybe just shorten the sentence: "You can click the *Browse* button to browse with the file explorer to specify where the data should be stored."?

2022-06-21 12:42 UTC, WeirdRubberDuck commented on docs/builders/ephemeris/horizons-gui.md
> +Here you can type in the name of the thing you want data for. For example if you want data for the Voyager 1 spacecraft you can write <code>Voyager 1</code> here. Horizons have data for many differen
I would rephrase so that not every section starts with "Here you...". Maybe "in this field". or just skip it completely where it doesn't seem needed?

2022-06-21 12:42 UTC, WeirdRubberDuck commented on docs/builders/ephemeris/horizons-gui.md
> +Here you can type in the name of the thing you want data for. For example if you want data for the Voyager 1 spacecraft you can write <code>Voyager 1</code> here. Horizons have data for many differen
Lin break before "In this field and the **Observer Location** field" ?

2022-06-21 12:42 UTC, WeirdRubberDuck commented on docs/builders/ephemeris/horizons-gui.md
> +Here you can type in the name of the thing you want data for. For example if you want data for the Voyager 1 spacecraft you can write <code>Voyager 1</code> here. Horizons have data for many differen
Also, "thing" sounds a bit vague. How about "object"? :)  Some improvement suggestion

"Here you can type in the name of the thing you want data for. For example if you want data for..."
->
"Here you specify the name of the object you want to get data for. For example, if you want data for..."

2022-06-21 12:42 UTC, WeirdRubberDuck commented on docs/builders/ephemeris/horizons-gui.md
> +Here you can type in the name of the thing you want data for. For example if you want data for the Voyager 1 spacecraft you can write <code>Voyager 1</code> here. Horizons have data for many differen
Actually: 
`"Here you specify the name of the object you want to get data for. For example, if you want data for the Voyager 1 spacecraft you can write <code>Voyager 1</code> here. Horizons have data for many different things from spacecraft, planets, moons, comets and asteroids to Lagrange points and more. 

In this and the **Observer Location** field the characters <code>¤ < > § £ ´ ¨ €</code> and other special characters from other languages are not allowed. Additionally, the characters <code>' =</code> have some limitations in how they can be used."

Might also be good to specify that "Voyager 1" must match an object in the Horizons framework and can't just be any name (right?)

2022-06-21 12:42 UTC, WeirdRubberDuck commented on docs/builders/ephemeris/horizons-gui.md
> +Here you can type in the name of the reference point you want for the data. For example if you want to show the movement of the spacecraft Voyager 1 over time, the reference point should probably be
"Here you specify the name of the reference point you want for the data. For example, if you want to show the movement of the spacecraft Voyager 1 over time, the reference point should probably be the Sun or the Solar System Barycenter. But if you instead want to show a satellite that orbits around Mars, the reference point should probably be Mars."

2022-06-21 12:42 UTC, WeirdRubberDuck commented on docs/builders/ephemeris/horizons-gui.md
> +Here you specify the start of the time range you want data for.
"The start of the time range you want data for."

An example f how to get rid of the "Here you.." repetitiveness. It's not really neede dhere
Could do the same for stop time

2022-06-21 12:42 UTC, WeirdRubberDuck commented on docs/builders/ephemeris/horizons-gui.md
> +Here you can select what format you want your data in, OpenSpace supports both **Vector Table** and **Observer Table**. However, we recommend the **Vector Table** format since this will give a better
Remove "can". "Here you select...."

This "can" can be removed from almost every section

2022-06-21 12:42 UTC, WeirdRubberDuck commented on docs/builders/ephemeris/horizons-gui.md
> +
Add a sentence: 

"The following sections describe the different parts of the Horizons UI. "

or something? För "röd tråd"?

2022-06-21 12:42 UTC, WeirdRubberDuck commented on docs/builders/ephemeris/horizons-gui.md
> +Here you can specify at what resolution you want the data to be in. You start with a number and then you can choose a time unit in the drop down menu to the right.
"The step size is the temporal resolution you want the data to have." 

And maybe an example, but the last sentence is not necessary :)

2022-06-21 12:42 UTC, WeirdRubberDuck commented on docs/builders/ephemeris/horizons-gui.md
> +There are a few different things that can go wrong while using this tool. Most of the issues are related to the input and can be fixed with some adjustments. The particular parameters that need to be
Add a sentence, för "röd tråd"

"Some common errors and solutions for those errors are explained below"

2022-06-21 12:42 UTC, WeirdRubberDuck commented on docs/builders/ephemeris/horizons-gui.md
> +The target you searched for found multiple matches in the Horizons database. There should be a added drop down menu close to the **Target Body** field where you can select one of the matches. If none
"There should be a added drop down menu ..."
->
"There should be an added drop-down menu ..."

2022-06-21 12:42 UTC, WeirdRubberDuck commented on docs/builders/ephemeris/horizons-gui.md
> +The observer location you searched for could not be found. Check that the name has been spelt correctly and you can also add a <code>@</code> to the beginning of the name to widen your search. If you
Split last sentence into two subsentences: 

"If you still cannot find what you are looking for, it is possible that there might be an alternative name for it in the Horizons database or that it does not exist."
?

2022-06-21 12:42 UTC, WeirdRubberDuck commented on docs/builders/ephemeris/horizons-gui.md
> +The observer you searched for found multiple matches in the Horizons database. There should be a added drop down menu close to the **Observer Location** field where you can select one of the matches.
"The observer you searched for found multiple matches in the Horizons database."
->
"Multiple matches were found in the Horizons database for the observer you searched for."  ?

2022-06-21 12:42 UTC, WeirdRubberDuck commented on docs/builders/ephemeris/horizons-gui.md
> +The observer you searched for found multiple matches in the Horizons database. There should be a added drop down menu close to the **Observer Location** field where you can select one of the matches.
"There should be a added drop down menu ..."
->
"There should be an added drop-down menu ..."

2022-06-21 12:42 UTC, WeirdRubberDuck commented on docs/builders/ephemeris/horizons-gui.md
> +The observer you searched for found multiple matching observer stations in the Horizons database. There should be a added drop down menu close to the **Observer Location** field where you can select
Same comment as above

2022-06-21 12:42 UTC, WeirdRubberDuck commented on docs/builders/ephemeris/horizons-gui.md
> +Each target has data available in a certain time range and this issue happens when you ask for data outside of that range. There should be a added button *Import Time Range* close to the time selecti
"There should be a added button..." -> "There should be an added button..."

2022-06-21 12:42 UTC, WeirdRubberDuck commented on docs/builders/ephemeris/horizons-gui.md
> +This problem arises when you ask for data over a very long time span and at the same time have a very fine resolution. Horizons data have a limit on how big the files can be and if the output is proj
This problem arises when you ask for data over a very long time span and at the same time have a very fine resolution. Horizons data have a limit on how big the files can be and if the output is projected to exceed that limit, this issue occurs. To fix this issue you need to either shorten the time span or decrease the resolution. In some cases, it might be necessary to do both. You can also separate your request into several files. For example, first you can ask for the first 10 years of data in one file and then ask for the remaining 10 years of data in a second file. These files can then be combined in OpenSpace to show all of the data without sacrificing the resolution.

2022-06-21 12:42 UTC, WeirdRubberDuck commented on docs/builders/ephemeris/horizons-web.md
> +This covers the basics of downloading ephemeris data for a solar system object from JPL Horizons webpage in the proper format for OpenSpace, and then configuring a renderable asset for it.  This docu
"the sun" -> "the Sun"

2022-06-21 12:42 UTC, WeirdRubberDuck commented on docs/builders/ephemeris/horizons-web.md
> +This wiki covers the scenario where an asset file references a data file served by one of the OpenSpace sync servers.  At runtime, the file will be downloaded if a local copy does not already exist.
"in the above steps" -> "in the steps above" ? maybe nitpicky

2022-06-21 12:42 UTC, WeirdRubberDuck commented on docs/builders/ephemeris/index.md
> +- [Using the GUI in OpenSpace to download Horizons data](horizons-gui)
Should be big Ds:    "Using the GUI in OpenSpace to Download Horizons Data" to match the format of the other page titles

2022-06-21 12:42 UTC, WeirdRubberDuck commented on docs/builders/ephemeris/horizons-gui.md
> +# Issues and Solutions
Nitpicky, but you vary what title casing you use. This should be "Issues and solutions" to match the ones below. Maybe look through them again and decide on a style?

2022-06-22 08:56 UTC, Roxeena commented on docs/builders/ephemeris/horizons-gui.md
> +Here you can type in the name of the thing you want data for. For example if you want data for the Voyager 1 spacecraft you can write <code>Voyager 1</code> here. Horizons have data for many differen
What do you mean that Voyager 1 has to be in the Horizons framework? This Works more or less lika a search and if there is no match there is an error that is explained further down.

2022-06-22 14:36 UTC, WeirdRubberDuck commented on docs/builders/ephemeris/horizons-gui.md
> +Here you can type in the name of the thing you want data for. For example if you want data for the Voyager 1 spacecraft you can write <code>Voyager 1</code> here. Horizons have data for many differen
I just thought that the "search" part could be worth clarifying here already. Maybe something like: 

"Here you specify the name of the object you want to get data for.  It is used as a search string and has to match something that exists in Horizons to get a successful result. "

But maybe that's "dumbifying" it, I don't know

2022-06-23 07:41 UTC, Roxeena commented on docs/builders/ephemeris/horizons-gui.md
> +Here you can type in the name of the thing you want data for. For example if you want data for the Voyager 1 spacecraft you can write <code>Voyager 1</code> here. Horizons have data for many differen
Since I have a section further down on how to solve that problem if it arises, I think I will leave it as it is for now.

2022-06-23 07:52 UTC, WeirdRubberDuck approved these changes

2022-06-23 09:04 UTC, merged